### ISSUE TITLE
关于c++的三目运算符

### ISSUE THREAD

**Issue by eleven-dimension** [Toseic/Generals-chess#1]
c++的三目运算符中第一个表达式才是条件吧，repo主是不是把它和python弄混淆了？
https://github.com/Toseic/Generals-chess/blob/15ffc9e588bc58ab37b65e2d528e5ae3f4ee2ded/judge.cpp#L226-L230

![image](https://user-images.githubusercontent.com/53202752/193392990-7c3c4fc5-3355-4331-99f5-6e166176d2d3.png)
[原link](https://cplusplus.com/articles/1AUq5Di1/)

**Comment by Toseic** [comment]
感谢指出这个错误
[https://github.com/Toseic/Generals-chess/commit/fbdd9bf87431ce9ee3d43a9eda7f79faf9ae2292](https://github.com/Toseic/Generals-chess/commit/fbdd9bf87431ce9ee3d43a9eda7f79faf9ae2292) 在这个commit里面已经修复了这个问题，
另外祝国庆快乐（\dog）

**Comment by eleven-dimension** [comment]
老哥你没改全。。
https://github.com/Toseic/Generals-chess/blob/fbdd9bf87431ce9ee3d43a9eda7f79faf9ae2292/judge.cpp#L439
https://github.com/Toseic/Generals-chess/blob/fbdd9bf87431ce9ee3d43a9eda7f79faf9ae2292/judge.cpp#L443
国庆快乐 😋

**Comment by Toseic** [comment]
刚才加注释的时候看到了，待会儿会加个commit

**Comment by Toseic** [comment]
新的一个commit把剩下两个也修复了
