### ISSUE TITLE
关于两只军队同时进攻一个中立城市

### ISSUE THREAD

**Issue by eleven-dimension** [Toseic/Generals-chess#2]
我测试了不同情况，发现有一种情况不太合理：比如中立城市原有驻军70，红方出兵60进攻，蓝方出兵30进攻，裁判的计算方式是先让红方先进攻，70 - 60 = 10，中立城市剩下10，然后再让蓝方进攻，30 - 10 = 20，但中立城市仍然处于中立状态，未被蓝方攻下。我觉得更合理的计算方式是先让红蓝两方交战，红方胜出后再和中立城市交战，70 - (60 - 30) = 40，中立城市剩下40。这一计算方式是在游戏[kingz](https://wiki.botzone.org.cn/index.php?title=Kingz)中采用的。主要是在[generals.io](https://generals.io/)上没有找到详细的规则，如果repo主有关于这一情形的战斗replay或者详细规则的话那就麻烦贴一下，thx 😋

**Comment by Toseic** [comment]
这种情况我在注释里面描述过。
这是我自己设定的规则，并没有考虑官方的规则或者kingz，我以前训练相关AI的时候留下来很多官方对局数据，过几天有空的时候我会去尝试在其中查找类似的对局情况。

**Comment by Toseic** [comment]
找到官方的规则的时候我会再回复，谢谢！

**Comment by Toseic** [comment]
简单的在数据集里面搜了一下：
前往 [https://generals.io/replays/B9PLBRMr_](https://generals.io/replays/B9PLBRMr_)
在左上角输入turn为57，向后两步，可以看到一次这种情况。
他的规则似乎不属于我的规则和kingz的规则中的任何一个
另外多说一下这种情况的出现概率：
<img width="1064" alt="截屏2022-10-02 15 56 43" src="https://user-images.githubusercontent.com/97432569/193444001-661c2cdb-4e5f-4166-89e9-d164553d3632.png">
这只是同时前往城市的数据，而同时前往中立城市的话搜起来比较麻烦，
但是可以预见的是，会非常非常少，我目前只见到了一次这种情况。

**Comment by eleven-dimension** [comment]
好的好的，非常感谢repo主:blush:
